/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as import0 from '@angular/core';
import * as import1 from '@angular/common';
import * as import2 from '../../../../src/app/about/about.component';
import * as import3 from '@angular/router';
const styles_AboutComponent:any[] = [''];
export const RenderType_AboutComponent:import0.RendererType2 = import0.ɵcrt({
  encapsulation: 0,
  styles: styles_AboutComponent,
  data: {}
}
);
export function View_AboutComponent_0(l:any):import0.ɵViewDefinition {
  return import0.ɵvid(0,[
    (l()(),import0.ɵted((null as any),['\n    '])),
    (l()(),import0.ɵeld(0,(null as any),(null as any),1,'h1',([] as any[]),(null as any),(null as any),(null as any),(null as any),(null as any))),
    (l()(),import0.ɵted((null as any),['About'])),
    (l()(),import0.ɵted((null as any),['\n    '])),
    (l()(),import0.ɵeld(0,(null as any),(null as any),4,'div',([] as any[]),(null as any),(null as any),(null as any),(null as any),(null as any))),
    (l()(),import0.ɵted((null as any),['\n      For hot module reloading run\n      '])),
    (l()(),import0.ɵeld(0,(null as any),(null as any),1,'pre',([] as any[]),(null as any),(null as any),(null as any),(null as any),(null as any))),
    (l()(),import0.ɵted((null as any),['npm run start:hmr'])),
    (l()(),import0.ɵted((null as any),['\n    '])),
    (l()(),import0.ɵted((null as any),['\n    '])),
    (l()(),import0.ɵeld(0,(null as any),(null as any),4,'div',([] as any[]),(null as any),(null as any),(null as any),(null as any),(null as any))),
    (l()(),import0.ɵted((null as any),['\n      '])),
    (l()(),import0.ɵeld(0,(null as any),(null as any),1,'h3',([] as any[]),(null as any),(null as any),(null as any),(null as any),(null as any))),
    (l()(),import0.ɵted((null as any),['\n        patrick@AngularClass.com\n      '])),
    (l()(),import0.ɵted((null as any),['\n    '])),
    (l()(),import0.ɵted((null as any),['\n    '])),
    (l()(),import0.ɵeld(0,(null as any),(null as any),2,'pre',([] as any[]),(null as any),(null as any),(null as any),(null as any),(null as any))),
    (l()(),import0.ɵted((null as any),[
      'this.localState = ',
      ''
    ]
    )),
    import0.ɵpid(0,import1.JsonPipe,([] as any[])),
    (l()(),import0.ɵted((null as any),['\n  ']))
  ]
  ,(null as any),(ck,v) => {
    var co:import2.AboutComponent = v.component;
    const currVal_0:any = import0.ɵunv(v,17,0,import0.ɵnov(v,18).transform(co.localState));
    ck(v,17,0,currVal_0);
  });
}
function View_AboutComponent_Host_0(l:any):import0.ɵViewDefinition {
  return import0.ɵvid(0,[
    (l()(),import0.ɵeld(0,(null as any),(null as any),1,'about',([] as any[]),(null as any),(null as any),(null as any),View_AboutComponent_0,RenderType_AboutComponent)),
    import0.ɵdid(57344,(null as any),0,import2.AboutComponent,[import3.ActivatedRoute],(null as any),(null as any))
  ]
  ,(ck,v) => {
    ck(v,1,0);
  },(null as any));
}
export const AboutComponentNgFactory:import0.ComponentFactory<import2.AboutComponent> = import0.ɵccf('about',import2.AboutComponent,View_AboutComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL2NocmlzdGFyYXNvdnMvRGVza3RvcC9naXRodWIvQW5ndWxhci10aGVtZS9zcmMvYXBwL2Fib3V0L2Fib3V0LmNvbXBvbmVudC5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9Vc2Vycy9jaHJpc3RhcmFzb3ZzL0Rlc2t0b3AvZ2l0aHViL0FuZ3VsYXItdGhlbWUvc3JjL2FwcC9hYm91dC9hYm91dC5jb21wb25lbnQudHMiLCJuZzovLy9Vc2Vycy9jaHJpc3RhcmFzb3ZzL0Rlc2t0b3AvZ2l0aHViL0FuZ3VsYXItdGhlbWUvc3JjL2FwcC9hYm91dC9hYm91dC5jb21wb25lbnQudHMuQWJvdXRDb21wb25lbnQuaHRtbCIsIm5nOi8vL1VzZXJzL2NocmlzdGFyYXNvdnMvRGVza3RvcC9naXRodWIvQW5ndWxhci10aGVtZS9zcmMvYXBwL2Fib3V0L2Fib3V0LmNvbXBvbmVudC50cy5BYm91dENvbXBvbmVudF9Ib3N0Lmh0bWwiXSwic291cmNlc0NvbnRlbnQiOlsiICIsIlxuICAgIDxoMT5BYm91dDwvaDE+XG4gICAgPGRpdj5cbiAgICAgIEZvciBob3QgbW9kdWxlIHJlbG9hZGluZyBydW5cbiAgICAgIDxwcmU+bnBtIHJ1biBzdGFydDpobXI8L3ByZT5cbiAgICA8L2Rpdj5cbiAgICA8ZGl2PlxuICAgICAgPGgzPlxuICAgICAgICBwYXRyaWNrQEFuZ3VsYXJDbGFzcy5jb21cbiAgICAgIDwvaDM+XG4gICAgPC9kaXY+XG4gICAgPHByZT50aGlzLmxvY2FsU3RhdGUgPSB7eyBsb2NhbFN0YXRlIHwganNvbiB9fTwvcHJlPlxuICAiLCI8YWJvdXQ+PC9hYm91dD4iXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7SUNBQTtJQUNJO0lBQUk7SUFBVTtJQUNkO0lBQUs7SUFFSDtJQUFLO0lBQXVCO0lBQ3hCO0lBQ047SUFBSztJQUNIO0lBQUk7SUFFQztJQUNEO0lBQ047SUFBSztNQUFBO01BQUE7SUFBQTtJQUFBO2dCQUFBO0lBQStDOzs7O0lBQS9DO0lBQUE7Ozs7O0lDWFQ7Z0JBQUE7OztJQUFBOzs7In0=
