/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as import0 from '@angular/core';
import * as import1 from '../../../../src/app/no-content/no-content.component';
const styles_NoContentComponent:any[] = ([] as any[]);
export const RenderType_NoContentComponent:import0.RendererType2 = import0.ɵcrt({
  encapsulation: 2,
  styles: styles_NoContentComponent,
  data: {}
}
);
export function View_NoContentComponent_0(l:any):import0.ɵViewDefinition {
  return import0.ɵvid(0,[
    (l()(),import0.ɵted((null as any),['\n    '])),
    (l()(),import0.ɵeld(0,(null as any),(null as any),4,'div',([] as any[]),(null as any),(null as any),(null as any),(null as any),(null as any))),
    (l()(),import0.ɵted((null as any),['\n      '])),
    (l()(),import0.ɵeld(0,(null as any),(null as any),1,'h1',([] as any[]),(null as any),(null as any),(null as any),(null as any),(null as any))),
    (l()(),import0.ɵted((null as any),['404: page missing'])),
    (l()(),import0.ɵted((null as any),['\n    '])),
    (l()(),import0.ɵted((null as any),['\n  ']))
  ]
  ,(null as any),(null as any));
}
function View_NoContentComponent_Host_0(l:any):import0.ɵViewDefinition {
  return import0.ɵvid(0,[
    (l()(),import0.ɵeld(0,(null as any),(null as any),1,'no-content',([] as any[]),(null as any),(null as any),(null as any),View_NoContentComponent_0,RenderType_NoContentComponent)),
    import0.ɵdid(24576,(null as any),0,import1.NoContentComponent,([] as any[]),(null as any),(null as any))
  ]
  ,(null as any),(null as any));
}
export const NoContentComponentNgFactory:import0.ComponentFactory<import1.NoContentComponent> = import0.ɵccf('no-content',import1.NoContentComponent,View_NoContentComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL2NocmlzdGFyYXNvdnMvRGVza3RvcC9naXRodWIvQW5ndWxhci10aGVtZS9zcmMvYXBwL25vLWNvbnRlbnQvbm8tY29udGVudC5jb21wb25lbnQubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vVXNlcnMvY2hyaXN0YXJhc292cy9EZXNrdG9wL2dpdGh1Yi9Bbmd1bGFyLXRoZW1lL3NyYy9hcHAvbm8tY29udGVudC9uby1jb250ZW50LmNvbXBvbmVudC50cyIsIm5nOi8vL1VzZXJzL2NocmlzdGFyYXNvdnMvRGVza3RvcC9naXRodWIvQW5ndWxhci10aGVtZS9zcmMvYXBwL25vLWNvbnRlbnQvbm8tY29udGVudC5jb21wb25lbnQudHMuTm9Db250ZW50Q29tcG9uZW50Lmh0bWwiLCJuZzovLy9Vc2Vycy9jaHJpc3RhcmFzb3ZzL0Rlc2t0b3AvZ2l0aHViL0FuZ3VsYXItdGhlbWUvc3JjL2FwcC9uby1jb250ZW50L25vLWNvbnRlbnQuY29tcG9uZW50LnRzLk5vQ29udGVudENvbXBvbmVudF9Ib3N0Lmh0bWwiXSwic291cmNlc0NvbnRlbnQiOlsiICIsIlxuICAgIDxkaXY+XG4gICAgICA8aDE+NDA0OiBwYWdlIG1pc3Npbmc8L2gxPlxuICAgIDwvZGl2PlxuICAiLCI8bm8tY29udGVudD48L25vLWNvbnRlbnQ+Il0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7Ozs7OztJQ0FBO0lBQ0k7SUFBSztJQUNIO0lBQUk7SUFBc0I7SUFDdEI7Ozs7OztJQ0hWO2dCQUFBOzs7OyJ9
