/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as import0 from '@angular/core';
import * as import1 from '../../../../../src/app/+barrel/+child-barrel/child-barrel.component';
const styles_ChildBarrelComponent:any[] = ([] as any[]);
export const RenderType_ChildBarrelComponent:import0.RendererType2 = import0.ɵcrt({
  encapsulation: 2,
  styles: styles_ChildBarrelComponent,
  data: {}
}
);
export function View_ChildBarrelComponent_0(l:any):import0.ɵViewDefinition {
  return import0.ɵvid(0,[
    (l()(),import0.ɵted((null as any),['\n    '])),
    (l()(),import0.ɵeld(0,(null as any),(null as any),1,'h1',([] as any[]),(null as any),(null as any),(null as any),(null as any),(null as any))),
    (l()(),import0.ɵted((null as any),['Hello from Child Barrel'])),
    (l()(),import0.ɵted((null as any),['    \n  ']))
  ]
  ,(null as any),(null as any));
}
function View_ChildBarrelComponent_Host_0(l:any):import0.ɵViewDefinition {
  return import0.ɵvid(0,[
    (l()(),import0.ɵeld(0,(null as any),(null as any),1,'child-barrel',([] as any[]),(null as any),(null as any),(null as any),View_ChildBarrelComponent_0,RenderType_ChildBarrelComponent)),
    import0.ɵdid(57344,(null as any),0,import1.ChildBarrelComponent,([] as any[]),(null as any),(null as any))
  ]
  ,(ck,v) => {
    ck(v,1,0);
  },(null as any));
}
export const ChildBarrelComponentNgFactory:import0.ComponentFactory<import1.ChildBarrelComponent> = import0.ɵccf('child-barrel',import1.ChildBarrelComponent,View_ChildBarrelComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL2NocmlzdGFyYXNvdnMvRGVza3RvcC9naXRodWIvQW5ndWxhci10aGVtZS9zcmMvYXBwLytiYXJyZWwvK2NoaWxkLWJhcnJlbC9jaGlsZC1iYXJyZWwuY29tcG9uZW50Lm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL1VzZXJzL2NocmlzdGFyYXNvdnMvRGVza3RvcC9naXRodWIvQW5ndWxhci10aGVtZS9zcmMvYXBwLytiYXJyZWwvK2NoaWxkLWJhcnJlbC9jaGlsZC1iYXJyZWwuY29tcG9uZW50LnRzIiwibmc6Ly8vVXNlcnMvY2hyaXN0YXJhc292cy9EZXNrdG9wL2dpdGh1Yi9Bbmd1bGFyLXRoZW1lL3NyYy9hcHAvK2JhcnJlbC8rY2hpbGQtYmFycmVsL2NoaWxkLWJhcnJlbC5jb21wb25lbnQudHMuQ2hpbGRCYXJyZWxDb21wb25lbnQuaHRtbCIsIm5nOi8vL1VzZXJzL2NocmlzdGFyYXNvdnMvRGVza3RvcC9naXRodWIvQW5ndWxhci10aGVtZS9zcmMvYXBwLytiYXJyZWwvK2NoaWxkLWJhcnJlbC9jaGlsZC1iYXJyZWwuY29tcG9uZW50LnRzLkNoaWxkQmFycmVsQ29tcG9uZW50X0hvc3QuaHRtbCJdLCJzb3VyY2VzQ29udGVudCI6WyIgIiwiXG4gICAgPGgxPkhlbGxvIGZyb20gQ2hpbGQgQmFycmVsPC9oMT4gICAgXG4gICIsIjxjaGlsZC1iYXJyZWw+PC9jaGlsZC1iYXJyZWw+Il0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7Ozs7OztJQ0FBO0lBQ0k7SUFBSTtJQUE0Qjs7Ozs7O0lDRHBDO2dCQUFBOzs7SUFBQTs7OyJ9
