/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as import0 from '@angular/core';
import * as import1 from '../../../../../src/app/+detail/+child-detail/child-detail.component';
const styles_ChildDetailComponent:any[] = ([] as any[]);
export const RenderType_ChildDetailComponent:import0.RendererType2 = import0.ɵcrt({
  encapsulation: 2,
  styles: styles_ChildDetailComponent,
  data: {}
}
);
export function View_ChildDetailComponent_0(l:any):import0.ɵViewDefinition {
  return import0.ɵvid(0,[
    (l()(),import0.ɵted((null as any),['\n    '])),
    (l()(),import0.ɵeld(0,(null as any),(null as any),1,'h1',([] as any[]),(null as any),(null as any),(null as any),(null as any),(null as any))),
    (l()(),import0.ɵted((null as any),['Hello from Child Detail'])),
    (l()(),import0.ɵted((null as any),['    \n  ']))
  ]
  ,(null as any),(null as any));
}
function View_ChildDetailComponent_Host_0(l:any):import0.ɵViewDefinition {
  return import0.ɵvid(0,[
    (l()(),import0.ɵeld(0,(null as any),(null as any),1,'child-detail',([] as any[]),(null as any),(null as any),(null as any),View_ChildDetailComponent_0,RenderType_ChildDetailComponent)),
    import0.ɵdid(57344,(null as any),0,import1.ChildDetailComponent,([] as any[]),(null as any),(null as any))
  ]
  ,(ck,v) => {
    ck(v,1,0);
  },(null as any));
}
export const ChildDetailComponentNgFactory:import0.ComponentFactory<import1.ChildDetailComponent> = import0.ɵccf('child-detail',import1.ChildDetailComponent,View_ChildDetailComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL2NocmlzdGFyYXNvdnMvRGVza3RvcC9naXRodWIvQW5ndWxhci10aGVtZS9zcmMvYXBwLytkZXRhaWwvK2NoaWxkLWRldGFpbC9jaGlsZC1kZXRhaWwuY29tcG9uZW50Lm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL1VzZXJzL2NocmlzdGFyYXNvdnMvRGVza3RvcC9naXRodWIvQW5ndWxhci10aGVtZS9zcmMvYXBwLytkZXRhaWwvK2NoaWxkLWRldGFpbC9jaGlsZC1kZXRhaWwuY29tcG9uZW50LnRzIiwibmc6Ly8vVXNlcnMvY2hyaXN0YXJhc292cy9EZXNrdG9wL2dpdGh1Yi9Bbmd1bGFyLXRoZW1lL3NyYy9hcHAvK2RldGFpbC8rY2hpbGQtZGV0YWlsL2NoaWxkLWRldGFpbC5jb21wb25lbnQudHMuQ2hpbGREZXRhaWxDb21wb25lbnQuaHRtbCIsIm5nOi8vL1VzZXJzL2NocmlzdGFyYXNvdnMvRGVza3RvcC9naXRodWIvQW5ndWxhci10aGVtZS9zcmMvYXBwLytkZXRhaWwvK2NoaWxkLWRldGFpbC9jaGlsZC1kZXRhaWwuY29tcG9uZW50LnRzLkNoaWxkRGV0YWlsQ29tcG9uZW50X0hvc3QuaHRtbCJdLCJzb3VyY2VzQ29udGVudCI6WyIgIiwiXG4gICAgPGgxPkhlbGxvIGZyb20gQ2hpbGQgRGV0YWlsPC9oMT4gICAgXG4gICIsIjxjaGlsZC1kZXRhaWw+PC9jaGlsZC1kZXRhaWw+Il0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7Ozs7OztJQ0FBO0lBQ0k7SUFBSTtJQUE0Qjs7Ozs7O0lDRHBDO2dCQUFBOzs7SUFBQTs7OyJ9
