/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as import0 from '@angular/core';
import * as import1 from '@angular/common';
import * as import2 from '../../../../../src/app/content/page/page.componet';
import * as import3 from '@angular/router';
const styles_contentPageComponent:any[] = ([] as any[]);
export const RenderType_contentPageComponent:import0.RendererType2 = import0.ɵcrt({
  encapsulation: 2,
  styles: styles_contentPageComponent,
  data: {}
}
);
export function View_contentPageComponent_0(l:any):import0.ɵViewDefinition {
  return import0.ɵvid(0,[
    (l()(),import0.ɵted((null as any),['\n  New data\n  '])),
    (l()(),import0.ɵeld(0,(null as any),(null as any),2,'pre',([] as any[]),(null as any),(null as any),(null as any),(null as any),(null as any))),
    (l()(),import0.ɵted((null as any),[
      '',
      '\n'
    ]
    )),
    import0.ɵpid(0,import1.JsonPipe,([] as any[])),
    (l()(),import0.ɵted((null as any),['\n\n'])),
    (l()(),import0.ɵted((null as any),['\n\n\n\n  ']))
  ]
  ,(null as any),(ck,v) => {
    var co:import2.contentPageComponent = v.component;
    const currVal_0:any = import0.ɵunv(v,2,0,import0.ɵnov(v,3).transform(co.postdata));
    ck(v,2,0,currVal_0);
  });
}
function View_contentPageComponent_Host_0(l:any):import0.ɵViewDefinition {
  return import0.ɵvid(0,[
    (l()(),import0.ɵeld(0,(null as any),(null as any),1,'page',([] as any[]),(null as any),(null as any),(null as any),View_contentPageComponent_0,RenderType_contentPageComponent)),
    import0.ɵdid(57344,(null as any),0,import2.contentPageComponent,[import3.ActivatedRoute],(null as any),(null as any))
  ]
  ,(ck,v) => {
    ck(v,1,0);
  },(null as any));
}
export const contentPageComponentNgFactory:import0.ComponentFactory<import2.contentPageComponent> = import0.ɵccf('page',import2.contentPageComponent,View_contentPageComponent_Host_0,{postdata: 'postdata'},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL2NocmlzdGFyYXNvdnMvRGVza3RvcC9naXRodWIvQW5ndWxhci10aGVtZS9zcmMvYXBwL2NvbnRlbnQvcGFnZS9wYWdlLmNvbXBvbmV0Lm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL1VzZXJzL2NocmlzdGFyYXNvdnMvRGVza3RvcC9naXRodWIvQW5ndWxhci10aGVtZS9zcmMvYXBwL2NvbnRlbnQvcGFnZS9wYWdlLmNvbXBvbmV0LnRzIiwibmc6Ly8vVXNlcnMvY2hyaXN0YXJhc292cy9EZXNrdG9wL2dpdGh1Yi9Bbmd1bGFyLXRoZW1lL3NyYy9hcHAvY29udGVudC9wYWdlL3BhZ2UuY29tcG9uZXQudHMuY29udGVudFBhZ2VDb21wb25lbnQuaHRtbCIsIm5nOi8vL1VzZXJzL2NocmlzdGFyYXNvdnMvRGVza3RvcC9naXRodWIvQW5ndWxhci10aGVtZS9zcmMvYXBwL2NvbnRlbnQvcGFnZS9wYWdlLmNvbXBvbmV0LnRzLmNvbnRlbnRQYWdlQ29tcG9uZW50X0hvc3QuaHRtbCJdLCJzb3VyY2VzQ29udGVudCI6WyIgIiwiXG4gIE5ldyBkYXRhXG4gIDxwcmU+XG57e3Bvc3RkYXRhIHwganNvbn19XG48L3ByZT5cblxuPCEtLVxuPHByZT5cbnt7cG9zdGRhdGEgfCBqc29ufX1cbjwvcHJlPlxue3twb3N0ZGF0YS5jb250ZW50LnJlbmRlcmVkfX1cblxuPGRpdiBbaW5uZXJIVE1MXT1cInBvc3RkYXRhLmNvbnRlbnQucmVuZGVyZWRcIj48L2Rpdj5cbiAgIDxkaXYgKm5nSWY9XCIocGFnZVNlY3Rpb25zIHwganNvbikgIT0gJ3t9J1wiID5cbiAgICAgIDxkaXYgKm5nRm9yPVwibGV0IHNlY3Rpb24gb2YgcGFnZVNlY3Rpb25zXCI+XG4gICAgICAgICAgPGRpdiBpZD1cInt7c2VjdGlvbi5hbmNob3JfbGlua319IFwiPlxuICAgICAgICAgICAgICAgIDxkaXYgY2xhc3M9XCJzZWN0aW9uLWltYWdlXCIgKm5nSWY9XCJzZWN0aW9uLnNlY3Rpb25faW1hZ2VcIiAgPlxuICAgICAgICAgICAgICAgICAgIDxpbWcgc3JjPVwie3tzZWN0aW9uLnNlY3Rpb25faW1hZ2Uuc2l6ZXMubGFyZ2V9fSBcIiAgLz5cbiAgICAgICAgICAgICAgICAgICB7e3NlY3Rpb24uc2VjdGlvbl9pbWFnZSB8IGpzb259fVxuICAgICAgICAgICAgICAgICAgPC9kaXY+XG4gICAgICAgICAgICAgICAgPGRpdiBbaW5uZXJIVE1MXT1cInNlY3Rpb24uc2VjdGlvbl9jb250ZW50XCI+PC9kaXY+XG4gICAgICAgICAgIDwvZGl2PlxuICAgICAgPC9kaXY+XG4gICA8L2Rpdj5cbi0tPlxuXG5cblxuICAiLCI8cGFnZT48L3BhZ2U+Il0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7O0lDQUE7SUFFRTtJQUFLO01BQUE7TUFBQTtJQUFBO0lBQUE7Z0JBQUE7SUFFRDtJQW9CSDs7OztJQXRCSTtJQUFBOzs7OztJQ0ZQO2dCQUFBOzs7SUFBQTs7OyJ9
