/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as import0 from '@angular/core';
import * as import1 from '../../../../src/app/+detail/detail.module';
import * as import2 from '@angular/common';
import * as import3 from '@angular/forms';
import * as import4 from '@angular/router';
import * as import5 from './detail.component.ngfactory';
import * as import6 from '../../../../src/app/+detail/detail.component';
class DetailModuleInjector extends import0.ɵNgModuleInjector<import1.DetailModule> {
  _CommonModule_0:import2.CommonModule;
  _ɵba_1:import3.ɵba;
  _FormsModule_2:import3.FormsModule;
  _RouterModule_3:import4.RouterModule;
  _DetailModule_4:import1.DetailModule;
  __NgLocalization_5:import2.NgLocaleLocalization;
  __ɵi_6:import3.ɵi;
  _ROUTES_7:any[];
  constructor(parent:import0.Injector) {
    super(parent,[import5.DetailComponentNgFactory],([] as any[]));
  }
  get _NgLocalization_5():import2.NgLocaleLocalization {
    if ((this.__NgLocalization_5 == null)) { (this.__NgLocalization_5 = new import2.NgLocaleLocalization(this.parent.get(import0.LOCALE_ID))); }
    return this.__NgLocalization_5;
  }
  get _ɵi_6():import3.ɵi {
    if ((this.__ɵi_6 == null)) { (this.__ɵi_6 = new import3.ɵi()); }
    return this.__ɵi_6;
  }
  createInternal():import1.DetailModule {
    this._CommonModule_0 = new import2.CommonModule();
    this._ɵba_1 = new import3.ɵba();
    this._FormsModule_2 = new import3.FormsModule();
    this._RouterModule_3 = new import4.RouterModule(this.parent.get(import4.ɵa,(null as any)),this.parent.get(import4.Router,(null as any)));
    this._DetailModule_4 = new import1.DetailModule();
        this._ROUTES_7 = [[{
          path: '',
          children: [
            {
              path: '',
              component: import6.DetailComponent
            }
            ,
            {
              path: 'child-detail',
              loadChildren: './+child-detail#ChildDetailModule'
            }

          ]

        }
    ]];
    return this._DetailModule_4;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import2.CommonModule)) { return this._CommonModule_0; }
    if ((token === import3.ɵba)) { return this._ɵba_1; }
    if ((token === import3.FormsModule)) { return this._FormsModule_2; }
    if ((token === import4.RouterModule)) { return this._RouterModule_3; }
    if ((token === import1.DetailModule)) { return this._DetailModule_4; }
    if ((token === import2.NgLocalization)) { return this._NgLocalization_5; }
    if ((token === import3.ɵi)) { return this._ɵi_6; }
    if ((token === import4.ROUTES)) { return this._ROUTES_7; }
    return notFoundResult;
  }
  destroyInternal():void {
  }
}
export const DetailModuleNgFactory:import0.NgModuleFactory<import1.DetailModule> = new import0.NgModuleFactory<any>(DetailModuleInjector,import1.DetailModule);
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL2NocmlzdGFyYXNvdnMvRGVza3RvcC9naXRodWIvQW5ndWxhci10aGVtZS9zcmMvYXBwLytkZXRhaWwvZGV0YWlsLm1vZHVsZS5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9Vc2Vycy9jaHJpc3RhcmFzb3ZzL0Rlc2t0b3AvZ2l0aHViL0FuZ3VsYXItdGhlbWUvc3JjL2FwcC8rZGV0YWlsL2RldGFpbC5tb2R1bGUudHMiXSwic291cmNlc0NvbnRlbnQiOlsiICJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OyJ9
